### ISSUE TITLE
Robots.txt not respected (for archive.mpi.nl)

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/linkchecker#25] opened 2021-10-11 07:18 UTC
Reported by the archive manager of The Language Archive (archive.mpi.nl): while [robots.txt](https://archive.mpi.nl/robots.txt) specifies:
```
User-agent: *
Crawl-delay: 10
```
The linkchecker at times makes requests with an interval of less than 3 seconds (23 checks per minute, see graph):
![image](https://user-images.githubusercontent.com/7011396/136748605-80e029ad-41b9-4a73-9157-574d3dc8281d.png)

![image](https://user-images.githubusercontent.com/7011396/136748879-b02c2131-0be0-4a4c-a0db-4559625154b3.png)

From this we can conclude that the linkchecker is *NOT* strictly respecting the robots.txt file in this case.

**Comment by twagoo** [comment] 2021-11-03 07:51
The production host was automatically banned from accessing the Danish repository server (fail2ban). Most likely this was due to too many requests. In this case we have another example of problematic over-requesting.

**Comment by wowasa** [comment] 2021-11-04 08:19
since we don't want content from get requests to be read, we set the property »http.content.limit: 0« in the yaml file. And this prevents also the content from the robots.txt file from being read and processed. 

I would qualify this as a bug in the storm crawler project which we can bypass easily, not by deactivating the setting, since we have some really large files (>50GB), where we don't want to load the content into memory, but by setting it to a value, which reads most robots.txt but prevents large files from being read completely.

**Comment by wowasa** [comment] 2021-11-04 13:37
version 2.1.2 will have »http.content.limit: 10000« which solves the issue. The issue is reported to the storm crawler project and qualified as a bug there (see https://github.com/DigitalPebble/storm-crawler/issues/921)

**Comment by wowasa** [comment] 2021-11-22 11:41
fixed with version 2.1.2

**Closed by wowasa** 2021-11-22 11:41 UTC
